name: "on-push"
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
#          - macos-10.15
#          - macos-11
          - macos-12
    steps:
    - uses: actions/checkout@master

    - name: Build
      run: ./build.sh
